export const tableNames = {
  USER: 'LD_USR_ADM',
  ROLE: 'LD_ROLE',
  ARTICLE: 'LD_ARTC',
  ARTICLE_DETAILS: 'LD_ART_DET',
  BANNER: 'LD_BNR',
  BANNER_ABOUT: 'LD_BNR_ABOUT',
  HOME_HEADLINE: 'LD_HOME_HD',
  PARTNER: 'LD_PRTNR',
  PARTNER_DETAILS: 'LD_PRTNR_DET',
  SERVICE_CATALOGUE_INTRO: 'LD_SVC_CAT_INT',
  SERVICE_CATALOGUE_FILE: 'LD_SVC_CAT_FILE',
  SOCIAL_MEDIA_CHANNEL: 'LD_SM_CHANNEL',
  EVENT: 'LD_EVT',
  EVENT_DETAILS: 'LD_EVT_DET',
}

export const roles = {
  SUPER_ADMIN: 'SUPER_ADMIN'
}